version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha1234  
      MYSQL_DATABASE: teste
      MYSQL_USER: Vini
      MYSQL_PASSWORD: Senha2023
    ports:
      - "3306:3306"
   

networks:
  mynetwork:
    driver: bridge
